name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-7240

trigger:
  branches:
    include:
    - feature/*
    - main
    - release/*

pr:
  branches:
    include:
    - main

parameters:
- name: location
  type: object
  displayName: 'Deployment locations (- westeurope & - northeurope)'
  default:
    - westeurope
    - northeurope
- name: kv
  type: boolean
  displayName: 'Deploy Key vault'
  default: false
- name: shaUse
  type: boolean
  displayName: 'Use Self Host agent'
  default: true
- name: tran
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global
- name: deployKv
  value: ${{parameters.kv}}

stages:

# Code Scans
- stage: scanInfra
  displayName: "Scan tools"
  jobs:

    - template:  pipeline/scanTools.yml@devopsTemplates
      parameters:
        AppDeploy: false 

- ${{ each location in parameters.location }}:
  - ${{ each parameter in parameters }}:
    - ${{ if in(parameter.key, 'tran','dev','test','pp','pr') }}:
      - ${{ if eq(parameter.value, 'true') }}:
        - ${{ if or(and(in(parameter.key, 'tran','pp','pr'),eq(location, 'northeurope')),and(in(parameter.key, 'tran','dev','test','pp','pr'),eq(location, 'westeurope'))) }}:
          - stage: Deployment_${{parameter.Key}}_${{location}}
            displayName: "Deployment [${{parameter.Key}}] ${{location}}"
            ${{ if or(eq(parameters.shaUse,'true'), eq(location,'northeurope')) }}:
              ${{ if or(eq(parameter.key, 'dev'), eq(parameter.key, 'tran')) }}:
                pool: Self-hosted Dev
              ${{ elseif eq(parameter.key, 'pr') }}:
                pool: Self-hosted Prod
              ${{ else }}:
                pool: Self-hosted Test
            ${{ if eq(location,'westeurope') }}:
              dependsOn: 
              - scanInfra
            ${{ if eq(location,'northeurope') }}:
              ${{ if eq(length(parameters.location), 2) }}:
                dependsOn: 
                - scanInfra
                - Deployment_${{parameter.key}}_westeurope
              ${{ else }}:
                dependsOn: 
                - scanInfra
            variables:
            - name: environmentId
              ${{ if eq(parameter.key, 'tran') }}:
                value: d03
              ${{ if eq(parameter.key, 'dev') }}:
                value: d01
              ${{ if eq(parameter.key, 'test') }}:
                value: t01
              ${{ if eq(parameter.key, 'pp') }}:
                value: t02
              ${{ if eq(parameter.key, 'pr') }}:
                value: p01
            jobs:
            - template: pipeline/infrastructure.yml@devopsTemplates
              parameters:
                ${{ if or(eq(parameter.key, 'dev'), eq(parameter.key, 'tran')) }}:
                  serviceConnection: $(devServiceConnection)
                ${{ elseif eq(parameter.key, 'pr') }}:
                  serviceConnection: $(prodServiceConnection)
                ${{ else }}:
                  serviceConnection: $(testServiceConnection)
                environmentName: ${{parameter.key}}
                deployPrivateEndpoint: "true"
                deployASP: "true" #Deploying the application service plans
                deploymentLocation: ${{location}}
