name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: main

trigger:
  branches:
    include:
    - release/*
    - feature/*

pr:
  branches:
    include:
    - main
    - develop

parameters:
- name: prereq
  type: boolean
  displayName: 'Deploy Pre-Requisites'
  default: false
- name: tran
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: int
  type: boolean
  displayName: 'INT Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global
- name: tran
  ${{ if or(eq(parameters.tran, 'true'), }}:
    value: true
  ${{ else }}:
    value: false
- name: dev
  ${{ if or(eq(parameters.dev, 'true')}}:
    value: true
  ${{ else }}:
    value: false
- name: test
  ${{ if or(eq(parameters.test, 'true'), contains(variables['Build.SourceBranch'],'develop')) }}:
    value: true
  ${{ else }}:
    value: false
- name: int
  ${{ if or(eq(parameters.int, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false
- name: pp
  ${{ if or(eq(parameters.pp, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false
- name: pr
  ${{ if or(eq(parameters.pr, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false
- name: brch
  value: $(Build.SourceBranchName)

stages:

# Code Scans & Build the artifact for deployment
- stage: scanInfra
  displayName: "Scan tools"
  jobs:
    # Code scaning tools
    - template:  pipeline/checkov.yml@devopsTemplates

- ${{ each parameter in parameters }}:
  - ${{ if ne(parameter.key, 'prereq') }}:
    - ${{ if eq(parameter.value, 'true') }}:
      - stage: Deployment_${{parameter.Key}}
        displayName: "Deployment [${{parameter.Key}}]"
        dependsOn: 
        - scanInfra
        variables:
        - group: dsi-${{parameter.key}}-kv
        jobs:
        - ${{ if parameters.prereq }}:
          - template: pipeline/preDeployInfrastrusture.yml@devopsTemplates
            parameters:
              ${{ if eq(parameter.key, 'dev') }}:
                serviceConnection: $(devServiceConnection)
              ${{ elseif eq(parameter.key, 'pr') }}:
                serviceConnection: $(prodServiceConnection)
              ${{ else }}:
                serviceConnection: $(testServiceConnection)
              environmentName: ${{parameter.key}}
              infrastuctureType: pre_req_infr

        - ${{ else }}:
          - template: pipeline/preDeployInfrastrusture.yml@devopsTemplates
            parameters:
              ${{ if eq(parameter.key, 'dev') }}:
                serviceConnection: $(devServiceConnection)
              ${{ elseif eq(parameter.key, 'pr') }}:
                serviceConnection: $(prodServiceConnection)
              ${{ else }}:
                serviceConnection: $(testServiceConnection)
              environmentName: ${{parameter.key}}
              infrastuctureType: base_infr
              templatePath:  $(System.DefaultWorkingDirectory)/login.dfe.infrastructure/DevOps/templates/template.json
              deployPrivateEndpoint: false