name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: main

trigger: none

pr: none

parameters:
  - name: location
    type: object
    displayName: 'Deployment locations (- westeurope & - northeurope)'
    default:
      - westeurope
      - northeurope
  - name: tran
    type: boolean
    displayName: 'Transformation Deployment'
    default: false
  - name: pp
    type: boolean
    displayName: 'Pre-Prod Deployment'
    default: false
  - name: pr
    type: boolean
    displayName: 'Prod Deployment'
    default: false

variables:
  - group: dsi-global
  - group: dsi-envs-list
  - name: BuildTagID
    value: $(BuildID)

stages:

  # Code Scans
  - stage: scanInfra
    displayName: "Scan tools"
    jobs:

      - template:  pipeline/scanTools.yml@devopsTemplates
        parameters:
          AppDeploy: false 

  - ${{ each location in parameters.location }}:
    - ${{ each parameter in parameters }}:
      - ${{ if and(in(parameter.key, 'tran','pp','pr'),eq(parameter.value, 'true')) }}:
        - stage: Deployment_${{parameter.Key}}_${{location}}
          displayName: "Deployment [${{parameter.Key}}] ${{location}}"
          ${{ if eq(location,'westeurope') }}:
            dependsOn: 
            - scanInfra
          ${{ if eq(location,'northeurope') }}:
            ${{ if eq(length(parameters.location), 2) }}:
              dependsOn: 
              - scanInfra
              - Deployment_${{parameter.key}}_westeurope
            ${{ else }}:
              dependsOn: 
              - scanInfra
          variables:
          - name: environmentId
            value: $[variables['${{parameter.key}}EnvId']]
          - name: ServConName
            value: ${{ format('{0}{1}', ${{parameter.key}}, 'ServCon') }}
          jobs:
          - template: pipeline/selfHostAgent.yml@devopsTemplates
            parameters:
              serviceConnection: $(${{variables.ServConName}})
              azpPool: $[variables['${{env}}ShaPool']]
              environmentName: ${{parameter.key}}
              deploymentLocation: ${{location}}
