name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: main

trigger:
  branches:
    include:
    - feature/*
    - main
    - release/*

pr:
  branches:
    include:
    - main

parameters:
  - name: location
    type: object
    displayName: 'Deployment locations (- westeurope & - northeurope)'
    default:
      - westeurope
      - northeurope
  - name: kv
    type: boolean
    displayName: 'Deploy Key vault'
    default: false
  - name: shaUse
    type: boolean
    displayName: 'Use Self Host agent'
    default: true
  - name: tran
    type: boolean
    displayName: 'Transformation Deployment'
    default: false
  - name: dev
    type: boolean
    displayName: 'Dev Deployment'
    default: false
  - name: test
    type: boolean
    displayName: 'Test Deployment'
    default: false
  - name: pp
    type: boolean
    displayName: 'Pre-Prod Deployment'
    default: false
  - name: pr
    type: boolean
    displayName: 'Prod Deployment'
    default: false

variables:
  - group: dsi-global
  - group: dsi-envs-list
  - name: deployKv
    value: ${{parameters.kv}}
  - name: northeurope
    value: 'tran,pp,pr'
  - name: westeurope
    value: 'tran,dev,test,pp,pr'

stages:

  # Code Scans
  - stage: scanInfra
    displayName: "Scan tools"
    jobs:

      - template:  pipeline/scanTools.yml@devopsTemplates
        parameters:
          AppDeploy: false 

  - ${{ each location in parameters.location }}:
    - ${{ each parameter in parameters }}:
      - ${{ if eq(parameters[env], 'true') }}:
        - stage: Deployment_${{parameter.Key}}_${{location}}
          displayName: "Deployment [${{parameter.Key}}] ${{location}}"
          ${{ if or(eq(parameters.shaUse,'true'), eq(location,'northeurope')) }}:
            pool: $[variables['${{parameter.key}}ShaPool']]
          ${{ if eq(location,'westeurope') }}:
            dependsOn: 
            - scanInfra
          ${{ if eq(location,'northeurope') }}:
            ${{ if eq(length(parameters.location), 2) }}:
              dependsOn: 
              - scanInfra
              - Deployment_${{parameter.key}}_westeurope
            ${{ else }}:
              dependsOn: 
              - scanInfra
          variables:
          - name: secRegionId
            value: $(${{ format('{0}{1}', location, 'Id') }})
          - name: environmentId
            value: $[variables['${{parameter.key}}EnvId']]
          - name: ServConName
            value: ${{ format('{0}{1}', parameter.key, 'ServCon') }}
          - name: ShaCodeName
            value: ${{ format('{0}{1}', env, 'ShaCode') }}
          jobs:
          - template: pipeline/infrastructure.yml@devopsTemplates
            parameters:
              serviceConnection: $(${{variables.ServConName}})
              environmentName: ${{parameter.key}}
              deployPrivateEndpoint: "true"
              deployASP: "true" #Deploying the application service plans
              deploymentLocation: ${{location}}
              shaUse: ${{parameters.shaUse}}
