name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: main

trigger:
  branches:
    include:
    - feature/*
    - develop
    - release/*

pr:
  branches:
    include:
    - develop

parameters:
- name: prereq
  type: boolean
  displayName: 'Deploy Pre-Requisites only'
  default: false
- name: tran
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global

stages:

# Code Scans & Build the artifact for deployment
- stage: scanInfra
  displayName: "Scan tools"
  jobs:
    # Code scaning tools
    - template:  pipeline/checkov.yml@devopsTemplates

- ${{ each parameter in parameters }}:
  - ${{ if in(parameter.key, 'tran','dev','test','pp','pr') }}:
    - ${{ if eq(parameter.value, 'true') }}:
      - stage: Deployment_${{parameter.Key}}
        displayName: "Deployment [${{parameter.Key}}]"
       # dependsOn: 
       #  - scanInfra
        variables:
        - group: dsi-${{parameter.key}}-kv
        jobs:
        - ${{ if parameters.prereq }}:
          - template: pipeline/infrastructure.yml@devopsTemplates
            parameters:
              ${{ if or(eq(parameter.key, 'dev'), eq(parameter.key, 'tran')) }}:
                serviceConnection: $(devServiceConnection)
              ${{ elseif eq(parameter.key, 'pr') }}:
                serviceConnection: $(prodServiceConnection)
              ${{ else }}:
                serviceConnection: $(testServiceConnection)
              environmentName: ${{parameter.key}}
              infrastuctureType: pre_req_infr

        - ${{ else }}:
          - template: pipeline/infrastructure.yml@devopsTemplates
            parameters:
              ${{ if or(eq(parameter.key, 'dev'), eq(parameter.key, 'tran')) }}:
                serviceConnection: $(devServiceConnection)
              ${{ elseif eq(parameter.key, 'pr') }}:
                serviceConnection: $(prodServiceConnection)
              ${{ else }}:
                serviceConnection: $(testServiceConnection)
              environmentName: ${{parameter.key}}
              infrastuctureType: base_infr
              templatePath:  $(System.DefaultWorkingDirectory)/login.dfe.infrastructure/DevOps/templates/template.json
              deployPrivateEndpoint: "true"
              destructiveVirtualNetworkDeploy: "Disabled" #Disabled,Enabled
              deployVirtualNetwork: "false" #Deploying the subnets
              deployASP: "false" #Deploying the application service plans
