name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-5680

# trigger:
#   branches:
#     include:
#       - master
#       - develop
#     #  - feature/*
#     # exclude:
#     # - feature/*

parameters:
- name: tran
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: int
  type: boolean
  displayName: 'INT Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global

stages:

# Code Scans & Build the artifact for deployment
- stage: scanGateway
  displayName: "Scan tools"
  jobs:
    # Code scaning tools
    - template:  pipeline/checkov.yml@devopsTemplates

- ${{ each parameter in parameters }}:
  - ${{ if eq(parameter.value, 'true') }}:
    - stage: Deployment_${{parameter.Key}}
      displayName: "Deployment [${{parameter.Key}}]"
      dependsOn: 
      - scanGateway
      variables:
      - group: dsi-${{parameter.key}}-kv
      jobs:
      - template: pipeline/gateway.yml@devopsTemplates
        parameters:
          ${{ if or(eq(parameter.key, 'dev'), eq(parameter.key, 'tran')) }}:
            serviceConnection: $(devServiceConnection)
          ${{ elseif eq(parameter.key, 'pr') }}:
            serviceConnection: $(prodServiceConnection)
          ${{ else }}:
            serviceConnection: $(testServiceConnection)
          environmentName: ${{parameter.key}}
          ${{ if eq(parameter.key, 'pr') }}:
            sslCertificateName: signin-generic
            isProduction: true
          ${{ else }}:
            sslCertificateName: non-prod-gateway
            isProduction: false