name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: main

trigger:
  branches:
    include:
    - feature/*
    - develop
    - release/*

pr:
  branches:
    include:
    - develop

parameters:
- name: location
  type: object
  displayName: 'Deployment locations (- westeurope & - northeurope)'
  default:
    - westeurope
    - northeurope
- name: prereq
  type: boolean
  displayName: 'Deploy Pre-Requisites only'
  default: false
- name: kv
  type: boolean
  displayName: 'Deploy Key vault only if Pre-Requisites selected'
  default: false
- name: tran
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global

stages:

# Code Scans & Build the artifact for deployment
- stage: scanInfra
  displayName: "Scan tools"
  jobs:
    # Code scaning tools
    - template:  pipeline/checkov.yml@devopsTemplates

- ${{ each location in parameters.location }}:
  - ${{ each parameter in parameters }}:
    - ${{ if in(parameter.key, 'tran','dev','test','pp','pr') }}:
      - ${{ if eq(parameter.value, 'true') }}:
        - ${{ if or(and(in(parameter.key, 'tran','pp','pr'),eq(location, 'northeurope')),and(in(parameter.key, 'tran','dev','test','pp','pr'),eq(location, 'westeurope'))) }}:
          - stage: Deployment_${{parameter.Key}}_${{location}}
            displayName: "Deployment [${{parameter.Key}}] ${{location}}"
            ${{ if eq(location,'westeurope') }}:
              ${{ if eq(parameter.key,'pr') }}:
                dependsOn: 
                - scanInfra
                - Deployment_pp_${{location}}
                condition: in(dependencies.Deployment_pp_westeurope.result, 'Succeeded', 'Skipped')
              ${{ else }}:
                dependsOn: 
                - scanInfra
            ${{ if eq(location,'northeurope') }}:
              ${{ if eq(length(parameters.location), 2) }}:
                dependsOn: 
                - scanInfra
                - Deployment_${{parameter.key}}_westeurope
              ${{ else }}:
                dependsOn: 
                - scanInfra
            variables:
            - name: environmentId
              ${{ if eq(parameter.key, 'tran') }}:
                value: d03
              ${{ if eq(parameter.key, 'dev') }}:
                value: d01
              ${{ if eq(parameter.key, 'test') }}:
                value: t01
              ${{ if eq(parameter.key, 'pp') }}:
                value: t02
              ${{ if eq(parameter.key, 'pr') }}:
                value: p01
            jobs:
            - ${{ if parameters.prereq }}:
              - template: pipeline/infrastructure.yml@devopsTemplates
                parameters:
                  ${{ if or(eq(parameter.key, 'dev'), eq(parameter.key, 'tran')) }}:
                    serviceConnection: $(devServiceConnection)
                  ${{ elseif eq(parameter.key, 'pr') }}:
                    serviceConnection: $(prodServiceConnection)
                  ${{ else }}:
                    serviceConnection: $(testServiceConnection)
                  environmentName: ${{parameter.key}}
                  infrastuctureType: pre_req_infr
                  deployKv: ${{parameters.kv}}
                  deploymentLocation: ${{location}}

            - ${{ else }}:
              - template: pipeline/infrastructure.yml@devopsTemplates
                parameters:
                  ${{ if or(eq(parameter.key, 'dev'), eq(parameter.key, 'tran')) }}:
                    serviceConnection: $(devServiceConnection)
                  ${{ elseif eq(parameter.key, 'pr') }}:
                    serviceConnection: $(prodServiceConnection)
                  ${{ else }}:
                    serviceConnection: $(testServiceConnection)
                  environmentName: ${{parameter.key}}
                  infrastuctureType: base_infr
                  templatePath:  $(System.DefaultWorkingDirectory)/login.dfe.infrastructure/DevOps/templates/template.json
                  deployPrivateEndpoint: "true"
                  destructiveVirtualNetworkDeploy: "Disabled" #Disabled,Enabled
                  deployVirtualNetwork: "true" #Deploying the subnets
                  deployASP: "true" #Deploying the application service plans
                  deploymentLocation: ${{location}}
